
server:
  port: 9000
  servlet:
    context-path: /api
    encoding:
      charset: utf-8
      enable: true
spring:
  h2:
    console:
      enabled: true
      path: /h2-console # console 접속 path
      settings:
        web-allow-others: true # local Host가 아닌 외부에서 접속 할 때
  datasource:
    driver-class-name: org.h2.Driver  # Database를 H2로 사용하겠다.
    url: jdbc:h2:~/test  # H2 접속 정보
    username: sa  # H2 접속 시 입력할 username 정보 (원하는 것으로 입력)
    password:  # H2 접속 시 입력할 password 정보 (원하는 것으로 입력)
#  mvc:
#    servlet:
#      load-on-startup: 1
